# Generated by Django 4.2.7 on 2026-06-08 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqrequest',
            name='material_requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfqrequest',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfqrequest',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='rfq_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'dwg', 'dxf', 'step', 'stp'])]),
        ),
    ]
