# Generated by Django 5.2.15 on 2026-06-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('process_image', models.ImageField(upload_to='capabilities/')),
                ('machinery_used', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manufacturing Capabilities',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='certifications/')),
            ],
        ),
        migrations.CreateModel(
            name='ExportMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('flag_image', models.ImageField(blank=True, null=True, upload_to='flags/')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Factory', 'Factory Building'), ('Floor', 'Production Floor'), ('Machinery', 'Machinery'), ('Warehouse', 'Warehouse'), ('Lab', 'Quality Lab'), ('Testing', 'Testing Equipment'), ('Dispatch', 'Loading & Dispatch Area')], max_length=50)),
                ('image', models.ImageField(upload_to='infrastructure/')),
            ],
        ),
    ]
